### ISSUE TITLE
Header menu in mobile view is incorrectly positioned.

### ISSUE THREAD

**Issue by frano-m** [ucscXena/xena-web#43]
The mobile header menu, when open, is incorrectly positioned - part of the Xena site is revealed between the header and the menu.

![image](https://user-images.githubusercontent.com/18710366/83988998-51213a80-a988-11ea-9606-fa2e16c1d5e0.png)

**Comment by frano-m** [comment]
@maryjgoldman would you mind checking staging to confirm this is now resolved? 

To test:

- Shrink browser width to its minimum width and toggle the menu open/closed.
- Repeat with the browser at approx. 50% screen width.

Thank you!

**Comment by maryjgoldman** [comment]
This looks great on my phone (iPhone 6)

**Comment by maryjgoldman** [comment]
Shrink browser width to its minimum width and toggle the menu open/closed. --> looks good
Repeat with the browser at approx. 50% screen width. --> looks good

I also tested on my iPhone 6 and it looks good.

(sorry about not reading the testing directions fully the first time!)

Thank you!
