### ISSUE TITLE
extra space at the top of web page (staging)

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-web#45]
On staging there is a bit more space at the top of the home page between the nav bar and 'UCSC Xena'. It isn't much but since it's nice to get more content above the fold and the old spacing looks good.

Current production: 
![Screen Shot 2020-06-09 at 1 39 54 PM](https://user-images.githubusercontent.com/13877333/84197424-c22f2380-aa56-11ea-8988-bb8a6e77a945.png)

On staging:
![Screen Shot 2020-06-09 at 1 40 07 PM](https://user-images.githubusercontent.com/13877333/84197438-c78c6e00-aa56-11ea-8866-43229d8b863f.png)

**Comment by NoopDog** [comment]
Hi @maryjgoldman 

This should be fixed on staging.

Can you review?


![image](https://user-images.githubusercontent.com/3239697/84704752-264a5f80-af0f-11ea-8232-eed8ee185d86.png)

Cheers and Thanks,
Dave

**Comment by maryjgoldman** [comment]
This looks great
